# Controls configuration file (TOML)

[keyboard]
up    = [ "w" ]
down  = [ "s" ]
left  = [ "a" ]
right = [ "d" ]

inventory = [ "e" ]
menu      = [ "ESC" ]
debug     = [ "F3" ]

[gamepad_0]
up    = [ "-axis1", "2" ]
down  = [ "+axis1", "1" ]
left  = [ "-axis0", "3" ]
right = [ "+axis0", "0" ]

inventory = [ "" ]
menu      = [ "" ]
debug     = [ "" ]
