# Controls configuration file (TOML)

[keyboard]
up    = [ "w" ]
down  = [ "s" ]
left  = [ "a" ]
right = [ "d" ]

inventory = [ "e" ]
menu =


[gamepad]
up    = [ "-axis1", "2" ]
down  = [ "+axis1", "1" ]
left  = [ "-axis0", "3" ]
right = [ "+axis0", "0" ]

#Up    = 2
#Down  = 0
#Left  = 3
#Right = 1

inventory =
