#!/bin/bash
# Basic script to create .fnt file from PNG image
# Usage: ./png2fnt [PNG FILE] [FNT FILE] [UNICODE RANGES..]
# Example: ./png2fnt font.png font.fnt 0-7f ff-ff
# If no Unicode ranges are specified, it will begin at 0x00

# Edit these variables to configure the font
width=$(identify "$1" | cut -f3 -d' ' | cut -f1 -d'x')
height=$(identify "$1" | cut -f3 -d' ' | cut -f2 -d'x')
char_width=6
char_height=12

echo "info face=\"$1\" size=$char_height bold=0 italic=0 charset=\"\" unicode=1 stretchH=100 smooth=0 aa=1 padding=0,0,0,0 spacing=0,0 outline=0
common lineHeight=$(($char_height/2)) base=$char_height scaleW=$width scaleH=$height pages=1 packed=0 alphaChnl=0 redChnl=4 greenChnl=4 blueChnl=4
page id=0 file=\"$1\"
chars count=$(($(($width/$char_width)) * $(($height/$char_height))))
" > "$2"

x=0
y=0
for range in "${@:3}"; do
	i=$((0x$(echo "$range" | cut -d'-' -f1)))
	e=$((0x$(echo "$range" | cut -d'-' -f2)))
	x=$(($i%$width))
	y=$(($i/$height/${#@}))
	while [ $i -lt $e ]; do
		while [ $x -lt $(($width/$char_width)) ]; do
			echo "char id=$i x=$(($x*$char_width)) y=$(($y*$char_height)) width=5 height=12 xoffset=0 yoffset=0 xadvance=0 page=0 chnl=15" >> "$2"
			i=$(($i+1))
			x=$(($x+1))
			done
		y=$(($y+1))
		x=0
	done
done
