const enums = @import("enums.zig");
const Direction = enums.Direction;

pub const Tile = packed struct {
    pub const size = 12;

    // 8 bits
    id: Id,

    // If the tile was generated by the game through world generation, this
    // will be true, if placed by a player, it will be false
    naturally_generated: bool,

    // The `grade` of a material. This can mean very different things dependin
    // on the tile in question. If a grass tile, this could mean how tall the
    // grass is and what seeds it contains. If an ore, it could dictate how
    // much metal you'll get from it
    // (4 different possibilities)
    grade: u2,

    // The damage level of the tile. This can be caused by player mining,
    // explosions, etc.
    // (8 different possibilities)
    damage: u3,

    // The direction the tile is facing
    // (4 different possibilities)
    direction: Direction,

    /// Categories should denote the basic qualities of a specific tile.
    /// While different submaterials (eg: grass and sand or cobblestone and brick)
    /// may have different hardnesses and sound, they're still collected with the
    /// same type of tool
    pub const Id = enum(u8) {
        air = 0,

        // Various kinds of soil, sand, gravel, etc.
        dirt = 8,
        grass,
        sand,
        // Variants:
        //  0 = soil
        // 16 = sand
        // 32 = gravel

        // Logs, planks, bamboo
        wood = 16,

        // Cobblestone, smooth stone, bricks, ore
        stone = 32,

        metal = 48,

        // Computers, wires, machines
        electronic = 64,

        water = 80,
        // Variants:
        //  0 = water
        // 16 = crude oil
        // 32 = melten stone

        misc = 240,

        // Tile dedicated to the `placeholder` texture
        placeholder = 255,
    };
};
