name: Automatic build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.0

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl-dev libxkbcommon-dev libegl-dev libwayland-dev zip

    - name: Build
      run: ./resources/build.sh

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: |
          *.AppImage
          *.shImg
          *.zsync
          *.zip
